services:

  recommendation_server:
    build:
      context: ../RecommendationSystem/
      dockerfile: Dockerfile
    ports:
      - "${RECOMMENDATION_SERVER_PORT:-8080}:${RECOMMENDATION_SERVER_PORT:-8080}"
    container_name: recommendation_server

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    env_file:
      - ./config/.env.prod
    environment:
      NODE_ENV: "prod"
      CONNECTION_STRING: "mongodb://mongo:${MONGO_PORT:-27017}"
      RECOMMENDATION_IP: "recommendation_server"
      RECOMMENDATION_PORT: "${RECOMMENDATION_SERVER_PORT:-8080}"
      PORT: "${APP_PORT:-3000}"
    depends_on:
      - mongo
    
  mongo:
    image: mongo:6
    container_name: mongodb1
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"
    volumes:
      - mongo_data:/data/db # Persist MongoDB data

volumes:
  mongo_data:
