services:

  recommendation_server:
    build:
      context: ../RecommendationSystem/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: recommendation_server

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "prod"
      CONNECTION_STRING: "mongodb://mongo:27017"
      RECOMMENDATION_IP: "recommendation_server"
      RECOMMENDATION_PORT: 8080
      PORT: "3000"
    depends_on:
      - mongo
    
  mongo:
    image: mongo:6
    container_name: mongodb1
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Persist MongoDB data

volumes:
  mongo_data:

