//
// Created by nimro on 05/12/2024.
//

#ifndef RECOMMENDATIONSYSTEM_TESTS_TEST_RECOMMENDALGO_H
#define RECOMMENDATIONSYSTEM_TESTS_TEST_RECOMMENDALGO_H


class test_recommendAlgo {

};


#endif //RECOMMENDATIONSYSTEM_TESTS_TEST_RECOMMENDALGO_H
